name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{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}}
          GIST_ID: ${{rawfishthelgh}}
          TIMEZONE: Asia/Seoul
